package calculadoraip;

/**
 *
 * @author AriasUwU
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        q1 = new javax.swing.JTextField();
        q2 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mascara = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        DireccionBin = new javax.swing.JLabel();
        MascaraBin = new javax.swing.JLabel();
        RedesBin = new javax.swing.JLabel();
        BroadcastBin = new javax.swing.JLabel();
        DirDec = new javax.swing.JLabel();
        MasDec = new javax.swing.JLabel();
        RedDec = new javax.swing.JLabel();
        BroDec = new javax.swing.JLabel();
        CT = new javax.swing.JLabel();
        HT = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Clase = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("IP");

        q1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        q1.setText("192");
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });

        q2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        q2.setText("168");

        q3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        q3.setText("254");
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });

        q4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        q4.setText("254");
        q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("/");

        mascara.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mascara.setText("24");
        mascara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mascaraActionPerformed(evt);
            }
        });

        Calcular.setText("CALCULAR");
        Calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalcularMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText(".");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText(".");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText(".");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Binario");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Dirección IP");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Máscara");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Red");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Broadcast");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Decimal");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Dirección IP");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Máscara");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Red");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Broadcast");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Conexiones totales");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Hosts totales");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Clase");

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("LIMPIAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel18))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HT)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Clase, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DirDec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                            .addComponent(MasDec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BroDec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(RedDec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DireccionBin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(MascaraBin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(RedesBin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BroadcastBin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                        .addComponent(jButton1))))))
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mascara, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Calcular))
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(q2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(q3)
                    .addComponent(jLabel5)
                    .addComponent(q4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mascara)
                    .addComponent(Calcular)
                    .addComponent(q1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(MascaraBin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(RedesBin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(BroadcastBin)))
                    .addComponent(DireccionBin))
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DirDec)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(MasDec))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(RedDec))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(BroDec))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(HT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Clase)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3ActionPerformed

    private void q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4ActionPerformed

    private void mascaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mascaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mascaraActionPerformed

    private void CalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcularMouseClicked
        //Filtrando resultados
        int octeto3 = Integer.valueOf(q3.getText());
        int octeto2 = Integer.valueOf(q2.getText());
        int octeto1 = Integer.valueOf(q1.getText());
        int octeto = Integer.valueOf(q4.getText());
        if ((octeto >= 0) && (octeto <= 255) && (octeto1 >= 0) && (octeto1 <= 255) && (octeto2 >= 0) && (octeto2 <= 255) && (octeto3 >= 0) && (octeto3 <= 255)) {
            String bq1 = Integer.toBinaryString(Integer.parseInt(q1.getText()));
                String bq2 = Integer.toBinaryString(Integer.parseInt(q2.getText()));
                String bq3 = Integer.toBinaryString(Integer.parseInt(q3.getText()));
                String bq4 = Integer.toBinaryString(Integer.parseInt(q4.getText()));
                //Se cambian a bytes de 8 dígitos
                String ipByte1 = String.format("%08d", Integer.parseInt(bq1));
                String ipByte2 = String.format("%08d", Integer.parseInt(bq2));
                String ipByte3 = String.format("%08d", Integer.parseInt(bq3));
                String ipByte4 = String.format("%08d", Integer.parseInt(bq4));
                //Creando la bitmask en enteros
                int bitMas = Integer.valueOf(mascara.getText());
                //Se genera un int de 32bits desde la dirección IP
                int DirBin = Integer.parseInt(ipByte1 + ipByte2 + ipByte3, 2);
                DirBin = (DirBin << 8) + Integer.parseInt(ipByte4, 2);
                //Generando la mascara de red de 32bit en binario
                int MasBin = ~0 << (32 - bitMas);
                //Operación para la dirección de Red
                int RedBin = DirBin & MasBin;
                //Operación para la dirección broadcast
                int BroBin = DirBin | ~MasBin;
                //dividiento el string con punto (".")
                String strDirBin = Integer.toBinaryString(DirBin);
                String[] printDirBin = strDirBin.split("(?<=\\G........)");
                String strMasBin = Integer.toBinaryString(MasBin);
                String[] printMasBin = strMasBin.split("(?<=\\G........)");
                String strRedBin = Integer.toBinaryString(RedBin);
                String[] printRedBin = strRedBin.split("(?<=\\G........)");
                String strBroBin = Integer.toBinaryString(BroBin);
                String[] printBroBin = strBroBin.split("(?<=\\G........)");
                //Display
                //Binario
                DireccionBin.setText(printDirBin[0] + "." + printDirBin[1] + "." + printDirBin[2] + "." + printDirBin[3]);
                MascaraBin.setText(printMasBin[0] + "." + printMasBin[1] + "." + printMasBin[2] + "." + printMasBin[3]);
                RedesBin.setText(printRedBin[0] + "." + printRedBin[1] + "." + printRedBin[2] + "." + printRedBin[3]);
                BroadcastBin.setText(printBroBin[0] + "." + printBroBin[1] + "." + printBroBin[2] + "." + printBroBin[3]);
                //Decimal
                DirDec.setText(q1.getText() + "." + q2.getText() + "." + q3.getText() + "." + q4.getText());
                MasDec.setText(String.valueOf(Integer.parseInt(printMasBin[0], 2)) + "."
                        + String.valueOf(Integer.parseInt(printMasBin[1], 2)) + "."
                        + String.valueOf(Integer.parseInt(printMasBin[2], 2)) + "."
                        + String.valueOf(Integer.parseInt(printMasBin[3], 2)));
                RedDec.setText(String.valueOf(Integer.parseInt(printRedBin[0], 2)) + "."
                        + String.valueOf(Integer.parseInt(printRedBin[1], 2)) + "."
                        + String.valueOf(Integer.parseInt(printRedBin[2], 2)) + "."
                        + String.valueOf(Integer.parseInt(printRedBin[3], 2)));
                BroDec.setText(String.valueOf(Integer.parseInt(printBroBin[0], 2)) + "."
                        + String.valueOf(Integer.parseInt(printBroBin[1], 2)) + "."
                        + String.valueOf(Integer.parseInt(printBroBin[2], 2)) + "."
                        + String.valueOf(Integer.parseInt(printBroBin[3], 2)));
                CT.setText(String.valueOf(~(~0 << bitMas)));
                HT.setText(String.valueOf(~MasBin));
                //Resolviendo tipo de clases
            if ((octeto >= 0) && (octeto <= 127)) {
                Clase.setText("Clase A");
            } else if ((octeto >= 128) && (octeto <= 191)) {
                Clase.setText("Clase B");
            } else if ((octeto >= 192) && (octeto <= 223)) {
                Clase.setText("Clase C");
            } else if ((octeto >= 224) && (octeto <= 239)) {
                Clase.setText("Clase D");
            } else if ((octeto >= 240) && (octeto <= 255)) {
                Clase.setText("Clase E");
            }
        } else if ((octeto > 255) || (octeto1 > 255) || (octeto2 > 255) || (octeto3 > 255)) {
            DireccionBin.setText("No existe en");
        MascaraBin.setText("rango de IPv4");
        RedesBin.setText("Intenta ingresando");
        BroadcastBin.setText("valores entre el");
        DirDec.setText("0 y el 255 en ");
        MasDec.setText("decimal");
        RedDec.setText(" ");
        BroDec.setText(" ");
        CT.setText(" ");
        HT.setText(" ");
            Clase.setText(" ");
        }
    }//GEN-LAST:event_CalcularMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DireccionBin.setText(" ");
        MascaraBin.setText(" ");
        RedesBin.setText(" ");
        BroadcastBin.setText(" ");
        DirDec.setText(" ");
        MasDec.setText(" ");
        RedDec.setText(" ");
        BroDec.setText(" ");
        CT.setText(" ");
        HT.setText(" ");
        Clase.setText(" ");
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BroDec;
    private javax.swing.JLabel BroadcastBin;
    private javax.swing.JLabel CT;
    private javax.swing.JButton Calcular;
    private javax.swing.JLabel Clase;
    private javax.swing.JLabel DirDec;
    private javax.swing.JLabel DireccionBin;
    private javax.swing.JLabel HT;
    private javax.swing.JLabel MasDec;
    private javax.swing.JLabel MascaraBin;
    private javax.swing.JLabel RedDec;
    private javax.swing.JLabel RedesBin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mascara;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    // End of variables declaration//GEN-END:variables
}
